baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Moon Cloud | A Cross Browser Testing Platform supporting Selenium, Cypress, Playwright and Puppeteer"

enableRobotsTXT = true


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
description = "A cross browser online testing platform. Fully compatible with Selenium Webdriver, Cypress, Playwright and Puppeteer. Automated and live testing. Runs in your desired cloud platform: Google Cloud, Amazon Web Services or Microsoft Azure. Runs in the region near you."
